Name:           ros-kinetic-cob-gazebo-ros-control
Version:        0.7.2
Release:        0%{?dist}
Summary:        ROS cob_gazebo_ros_control package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://ros.org/wiki/cob_gazebo_ros_control
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-controller-manager
Requires:       ros-kinetic-gazebo-ros
Requires:       ros-kinetic-gazebo-ros-control
Requires:       ros-kinetic-hardware-interface
Requires:       ros-kinetic-joint-limits-interface
Requires:       ros-kinetic-pluginlib
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-transmission-interface
Requires:       ros-kinetic-urdf
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-controller-manager
BuildRequires:  ros-kinetic-gazebo-ros
BuildRequires:  ros-kinetic-gazebo-ros-control
BuildRequires:  ros-kinetic-hardware-interface
BuildRequires:  ros-kinetic-joint-limits-interface
BuildRequires:  ros-kinetic-pluginlib
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-transmission-interface
BuildRequires:  ros-kinetic-urdf

%description
This package contains a specialization of the gazebo_ros_control plugin. The
cob_gazebo_ros_control plugin allows Multi-HardwareInterface-Support.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Sun Jan 07 2018 Felix Messmer <fxm@ipa.fhg.de> - 0.7.2-0
- Autogenerated by Bloom

* Mon Jul 17 2017 Felix Messmer <fxm@ipa.fhg.de> - 0.7.1-0
- Autogenerated by Bloom

